version: '3'

services:

  pastebin:
    container_name: pastebin
    image: pastebin:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=pastebin_db
      - POSTGRES_USER=pb_user
      - POSTGRES_PASSWORD=pb_pass
    ports:
      - "5432:5432"
    restart: always