-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS paste_tag
(
    id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    paste_hash VARCHAR(6) NOT NULL REFERENCES paste(hash) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tag(id) ON DELETE CASCADE,
    CONSTRAINT paste_tag_unique UNIQUE (paste_hash, tag_id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS paste_tag;
-- +goose StatementEnd
