-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS tag
(
    id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT name_unique UNIQUE (name)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS tag;
-- +goose StatementEnd
