version: '3'

services:

  pastebin:
    container_name: pastebin
    image: pastebin:latest
    build:
      context: ../..
      dockerfile: ./build/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    command: ["sh", "-c", "/app/pastebin"]

  db:
    container_name: pastebin-db
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always

  migrator:
    container_name: db-migrator
    image: migrator:latest
    build:
      context: ../..
      dockerfile: ./build/Dockerfile-goose
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "/app/goose -dir /app/migrations up"]


  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui-docker
    ports:
      - "8001:8080"
    environment:
      URLS: "[{ url: \"http://localhost:8080/api/v1/swagger/openapi.json\", name: \"Pastebin\" },]"